version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.9  # Use a Python image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run black
          command: |
            . venv/bin/activate
            black --check .
      - run:
          name: Run isort
          command: |
            . venv/bin/activate
            isort --check-only .
      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            flake8 .
      - persist_to_workspace:
          root: .
          paths:
            - venv

  test:
    docker:
      - image: cimg/python:3.9  # Use a Python image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2
  lint-and-test-workflow:
    jobs:
      - lint
      - test:
          requires:
            - lint